CRITICAL - 2024-09-04 00:09:27 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(26): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 00:26:30 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(26): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 01:40:46 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(26): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 02:23:12 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(26): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 02:27:36 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(26): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 02:52:53 --> ErrorException: Undefined variable $libro_id
[Method: GET, Route: ver_autoli]
in APPPATH\Views\Autolis.php on line 64.
 1 APPPATH\Views\Autolis.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $libro_id', 'C:\\xampp\\htdocs\\2024\\parcial\\app\\Views\\Autolis.php', 64)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\2024\\parcial\\app\\Views\\Autolis.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('Autolis', [], true)
 5 APPPATH\Controllers\ControladorAutoli.php(15): view('Autolis', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 02:52:56 --> ErrorException: Undefined variable $libro_id
[Method: GET, Route: ver_autoli]
in APPPATH\Views\Autolis.php on line 64.
 1 APPPATH\Views\Autolis.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $libro_id', 'C:\\xampp\\htdocs\\2024\\parcial\\app\\Views\\Autolis.php', 64)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\2024\\parcial\\app\\Views\\Autolis.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('Autolis', [], true)
 5 APPPATH\Controllers\ControladorAutoli.php(15): view('Autolis', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:01:17 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(33): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:01:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/2]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(33): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:01:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(33): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:01:17 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(33): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:04:39 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:04:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/2]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:04:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:04:39 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:10:09 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:10:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/2]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:10:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:10:09 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('2')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:10:15 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:10:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:10:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:10:15 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:38:04 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "frm_actualizar_depto.php"
[Method: GET, Route: datos_libro/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('frm_actualizar_depto.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('frm_actualizar_depto', [], true)
 3 APPPATH\Controllers\ControladorAutoli.php(44): view('frm_actualizar_depto', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verDatosLibro('1')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:38:08 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:38:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:38:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:38:08 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:38:12 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "frm_actualizar_depto.php"
[Method: GET, Route: datos_libro/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('frm_actualizar_depto.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('frm_actualizar_depto', [], true)
 3 APPPATH\Controllers\ControladorAutoli.php(44): view('frm_actualizar_depto', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verDatosLibro('1')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:41:16 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in C:\xampp\htdocs\2024\parcial\system\BaseModel.php on line 1875
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('14')
 2 SYSTEMPATH\BaseModel.php(997): CodeIgniter\BaseModel->transformDataToArray('14', 'update')
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], '14')
 4 APPPATH\Controllers\ControladorAutoli.php(55): CodeIgniter\Model->update('2', '14')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:45:03 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(55): CodeIgniter\Model->update('1', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:45:21 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(27): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:45:24 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:45:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:45:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:45:24 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:47:10 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(55): CodeIgniter\Model->update('1', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 03:47:17 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 03:47:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:47:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 03:47:17 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 04:11:41 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(36): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 04:11:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(36): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:11:41 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(36): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:11:41 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(36): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:11:46 --> ErrorException: Undefined variable $codigo
[Method: GET, Route: datos_libro/1]
in APPPATH\Controllers\ControladorAutoli.php on line 44.
 1 APPPATH\Controllers\ControladorAutoli.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $codigo', 'C:\\xampp\\htdocs\\2024\\parcial\\app\\Controllers\\ControladorAutoli.php', 44)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verDatosLibro('1')
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:15:37 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(27): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 04:15:45 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 04:15:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:15:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:15:45 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:16:53 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in C:\xampp\htdocs\2024\parcial\system\BaseModel.php on line 1875
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('10')
 2 SYSTEMPATH\BaseModel.php(997): CodeIgniter\BaseModel->transformDataToArray('10', 'update')
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], '10')
 4 APPPATH\Controllers\ControladorAutoli.php(55): CodeIgniter\Model->update('1', '10')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 04:17:00 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 04:17:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:17:00 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:17:00 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:43:58 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in C:\xampp\htdocs\2024\parcial\system\BaseModel.php on line 1875
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('10')
 2 SYSTEMPATH\BaseModel.php(997): CodeIgniter\BaseModel->transformDataToArray('10', 'update')
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], '10')
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('1', '10')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:46:40 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(23): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:46:50 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in C:\xampp\htdocs\2024\parcial\system\BaseModel.php on line 1875
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('11')
 2 SYSTEMPATH\BaseModel.php(997): CodeIgniter\BaseModel->transformDataToArray('11', 'update')
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], '11')
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('1', '11')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 04:46:56 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `au...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `au...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `au...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `au...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(31): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 04:46:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
[Method: GET, Route: eliminar_libro/1]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\ControladorAutoli.php(31): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:46:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\ControladorAutoli.php(31): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:46:56 --> [Caused by] mysqli_sql_exception: Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `autores_libros`
WHERE `id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2843): CodeIgniter\Database\BaseConnection->query('DELETE FROM `autores_libros`
WHERE `id` IN :id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\ControladorAutoli.php(31): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->eliminarLibro('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:59:26 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in C:\xampp\htdocs\2024\parcial\system\BaseModel.php on line 1875
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('12')
 2 SYSTEMPATH\BaseModel.php(997): CodeIgniter\BaseModel->transformDataToArray('12', 'update')
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], '12')
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('1', '12')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 04:59:52 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(23): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:09:13 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:13:26 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:16:22 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autoli"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autoli')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(51): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:28:05 --> Error: Class "App\Models\autores_libros" not found
[Method: GET, Route: datos_libro/2]
in APPPATH\Controllers\ControladorAutoli.php on line 38.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verDatosLibro('2')
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:28:05 --> Error: Class "App\Models\autores_libros" not found
[Method: GET, Route: ver_autoli]
in APPPATH\Controllers\ControladorAutoli.php on line 10.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:28:12 --> Error: Class "App\Models\autores_libros" not found
[Method: GET, Route: ver_autoli]
in APPPATH\Controllers\ControladorAutoli.php on line 10.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:30:09 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\autores_libros"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\autores_libros')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(50): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:34:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "autores_libros.php"
[Method: GET, Route: ver_autoli]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('autores_libros.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('autores_libros', [], true)
 3 APPPATH\Controllers\ControladorAutoli.php(11): view('autores_libros', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 05:36:49 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\autores_libros"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\autores_libros')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(50): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:28:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: GET, Route: eliminar_autor/0]
in SYSTEMPATH\Database\BaseBuilder.php on line 2814.
 1 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete('0', false)
 3 APPPATH\Controllers\ControladorAutor.php(44): CodeIgniter\BaseModel->delete('0')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->eliminarAutor('0')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:28:29 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "frm_actualizar_artista.php"
[Method: GET, Route: datos_autor/0]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('frm_actualizar_artista.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('frm_actualizar_artista', [], true)
 3 APPPATH\Controllers\ControladorAutor.php(54): view('frm_actualizar_artista', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->verDatosAutor('0')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:33:30 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autor"
[Method: POST, Route: actualizar_autor]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autor')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutor.php(74): CodeIgniter\Model->update('0', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->actualizarAutor()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:34:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Deletes are not allowed unless they contain a "where" or "like" clause.
[Method: GET, Route: eliminar_autor/0]
in SYSTEMPATH\Database\BaseBuilder.php on line 2814.
 1 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 2 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete('0', false)
 3 APPPATH\Controllers\ControladorAutor.php(44): CodeIgniter\BaseModel->delete('0')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->eliminarAutor('0')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 06:57:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'libros_ammy', 3306, '', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\2024\parcial\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutoli.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-09-04 06:57:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: ver_autoli]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `autores_libros`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ControladorAutoli.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->verAutoli()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 06:57:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'libros_ammy', 3306, '', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\2024\parcial\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-09-04 06:57:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: ver_autor]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Autores`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:59:06 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\autores_libros"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\autores_libros')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(22): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 06:59:17 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\autores_libros"
[Method: POST, Route: actualizar_libro]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\autores_libros')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutoli.php(50): CodeIgniter\Model->update('2', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->actualizarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 07:04:56 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\autores_libros"
[Method: POST, Route: agregar_libro]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\autores_libros')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutoli.php(22): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutoli->agregarLibro()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutoli))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-04 07:59:41 --> mysqli_sql_exception: Table 'libros_ammy.autores' doesn't exist in C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\2024\parcial\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\2024\parcial\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\2024\parcial\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\2024\parcial\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\2024\parcial\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\2024\parcial\app\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
#8 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
#9 C:\xampp\htdocs\2024\parcial\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\2024\parcial\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\2024\parcial\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\2024\parcial\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-09-04 07:59:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'libros_ammy.autores' doesn't exist
[Method: GET, Route: ver_autor]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Autores`', [], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 07:59:41 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'libros_ammy.autores' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `Autores`')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `Autores`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Autores`', [], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 07:59:41 --> [Caused by] mysqli_sql_exception: Table 'libros_ammy.autores' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *
FROM `Autores`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `Autores`')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `Autores`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Autores`', [], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\ControladorAutor.php(13): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->verAutor()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 08:07:01 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autor"
[Method: POST, Route: agregar_autor]
in SYSTEMPATH\Model.php on line 824.
 1 SYSTEMPATH\Model.php(824): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autor')
 2 SYSTEMPATH\BaseModel.php(821): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\ControladorAutor.php(35): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->agregarAutor()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-04 08:11:20 --> CodeIgniter\Database\Exceptions\DataException: Allowed fields must be specified for model: "App\Models\Autor"
[Method: POST, Route: actualizar_autor]
in SYSTEMPATH\BaseModel.php on line 1339.
 1 SYSTEMPATH\BaseModel.php(1339): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Autor')
 2 SYSTEMPATH\BaseModel.php(1006): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 4 APPPATH\Controllers\ControladorAutor.php(74): CodeIgniter\Model->update('5', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ControladorAutor->actualizarAutor()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControladorAutor))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
